server:
  context-path: /wechatMall
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechatmall
    username: root
    password: 111
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  #exclude empty attributes
weChat:
  mpAppId: wx4f577e3abaa4a19b
  mpAppSecret: shidiankeji9999
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

appUrl:
  weChatMpAuthorize: http://sell.natapp4.cc
  weChatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc


#TRACE < DEBUG < INFO < WARN < ERROR < FATAL
#logging:
#  level:
#    com.daniel.dao: DEBUG

#  #If used file and path at the same time, only file takes effect

#  #path: D:\wechatMall\log\
#  pattern:
#    #file: D:\wechatMall\logfile\mall.log
#    #console: "%d - %msg%n"

