spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechatmall
    username: root
    password: 111
  jpa:
    show-sql: true
server:
  context-path: /wechatMall

#TRACE < DEBUG < INFO < WARN < ERROR < FATAL
#logging:
#  level:
#    com.daniel.dao: DEBUG

#  #If used file and path at the same time, only file takes effect

#  #path: D:\wechatMall\log\
#  pattern:
#    #file: D:\wechatMall\logfile\mall.log
#    #console: "%d - %msg%n"

